In [1]:
import sys
sys.path.append('..') # Add path to the directory of qaoa-loan-collection

import numpy as np
from src.helpers import generate_random_dataset

from src.loanee_graph import LoaneeGraph
from src.qaoa_analytics import QaoaAnalytics
from src.helpers import generate_random_dataset
from src.result import ResultQaoa

In [2]:
rng = np.random.default_rng(12345)
e_54, a_54 = generate_random_dataset(5,4, seed=123)

config = {
    "epsilon_constant": 0.5,
    "qaoa_repetition": 2
}

l_54 = LoaneeGraph(e_54, a_54)
qaoa_54 = QaoaAnalytics(l_54, config)

initial_params = rng.random(4)
result = qaoa_54.optimize_qaoa_params(initial_params)

print(result)

ResultQaoa:
    Convergence      = False
    Length           = 50
    Optimized Cost   = -1.2434888994246909
    Optimized Params = [-0.02761005 -0.87741622  1.82102422 -0.092692  ]


In [3]:
result.get_optimized_cost()

-1.2434888994246909

In [4]:
result.get_optimized_params()

array([-0.02761005, -0.87741622,  1.82102422, -0.092692  ])

In [5]:
result.is_success()

False

In [6]:
result.get_list_costs()

[-1.1575493818573401,
 -1.1575493818573401,
 -0.9660634906804199,
 -1.2009342243553578,
 -1.197215457853933,
 -1.2094832359833336,
 -1.0323597382243361,
 -1.2094832359833338,
 -1.206314191476034,
 -1.2102753625457439,
 -1.0030784217075892,
 -1.2227356039814867,
 -1.2133288596346434,
 -1.2182153589924347,
 -1.2252812397924175,
 -1.2252812397924175,
 -1.2194952646094366,
 -1.220071409042989,
 -1.229004726903228,
 -1.2328995865851333,
 -1.2273541941721746,
 -1.2333125810118823,
 -1.232239013845131,
 -1.232839629884228,
 -1.2354405103351653,
 -1.2355193979954833,
 -1.2361788196079524,
 -1.234497230207035,
 -1.2364513314750085,
 -1.2378379354225884,
 -1.2373915926107104,
 -1.2385366202216206,
 -1.238435425238395,
 -1.2385416355451278,
 -1.2387265525640625,
 -1.2374754364378677,
 -1.2395397593180064,
 -1.2402354899808903,
 -1.240887788144601,
 -1.2412260308204717,
 -1.2418400149842403,
 -1.242263187083551,
 -1.2423813475842098,
 -1.2426783943310309,
 -1.2414971417147909,
 -1.2428282760072522

In [7]:
result.get_list_params()

[array([0.22733602, 0.31675834, 0.79736546, 0.67625467]),
 array([1.22733602, 0.31675834, 0.79736546, 0.67625467]),
 array([0.22733602, 1.31675834, 0.79736546, 0.67625467]),
 array([0.22733602, 0.31675834, 1.79736546, 0.67625467]),
 array([0.22733602, 0.31675834, 1.79736546, 1.67625467]),
 array([ 0.22733602, -0.65834765,  2.01829463,  0.65731755]),
 array([ 0.22733602, -0.64532345,  2.51629885,  0.61463072]),
 array([-0.02266398, -0.65834765,  2.01829463,  0.65731755]),
 array([-0.02266398, -0.78013626,  1.53338069,  0.65221867]),
 array([-0.02266398, -0.65319155,  2.01962781,  0.40737428]),
 array([-0.02266398, -0.95740531,  2.38878193,  0.26184344]),
 array([-0.02266398, -0.16691293,  1.90347648,  0.41385322]),
 array([-0.02266398,  0.08177582,  1.90456046,  0.38830464]),
 array([-0.02266398, -0.17402336,  2.01020214,  0.34916878]),
 array([-0.02266398, -0.2443488 ,  1.73063514,  0.25066756]),
 array([-0.14766398, -0.2443488 ,  1.73063514,  0.25066756]),
 array([-0.02266398, -0.4086

In [8]:
result.get_params_with_index(5)

array([ 0.22733602, -0.65834765,  2.01829463,  0.65731755])

In [9]:
result.get_cost_with_index(3)

-1.2009342243553578